# Site wide configuration

title: Natália Assis
description: Languages & Communications
logo: natalia-apple-120x120.jpg
teaser: natalia-apple-400x250.jpg
locale: en
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Natália Assis
  email: nnatalia@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio: All things language & communication
  avatar: natalia-apple-160x160.jpg
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
